# -*- coding: utf-8 -*-
"""
04_run_baseline_forecasting.py

Baseline forecasting experiments for the validated Saildrone SD1090 dataset.

Baseline models
---------------
1. Persistence
   The future U/V vector is assumed to remain equal to the last observed U/V
   vector at the end of the 60-min input context.

2. Ridge regression
   The complete standardized input sequence is flattened:
       [lookback, features] -> [lookback * features]
   and a multi-output ridge model predicts all standardized future U/V targets:
       [horizons, 2] -> [horizons * 2]

Protocol
--------
- Requires a forecasting dataset produced by 02_build_forecasting_dataset.py.
- By default requires a VALIDATION_PASSED.flag generated by
  03_validate_forecasting_dataset.py.
- Ridge alpha is selected ONLY on the validation split.
- Test data are not used for model fitting or hyperparameter selection.
- The selected Ridge model remains fitted on TRAIN only, keeping the protocol
  aligned with later neural-network experiments that use validation for model
  selection/early stopping.
- Standardization is inherited unchanged from the frozen dataset and therefore
  remains TRAIN-only.

Primary selection criterion
---------------------------
Mean vector RMSE over all forecast horizons on the validation split:

    vector_RMSE(h) = sqrt(mean[(U_hat-U)^2 + (V_hat-V)^2])

The validation score for alpha selection is the arithmetic mean across horizons.

Metrics reported per horizon
----------------------------
- U_RMSE
- V_RMSE
- vector_RMSE
- U_MAE
- V_MAE
- vector_MAE
- speed_RMSE
- speed_MAE
- R2_U
- R2_V
- R2_mean
- skill_vs_persistence

where:
    speed = sqrt(U^2 + V^2)
    skill = 1 - model_vector_RMSE / persistence_vector_RMSE

Outputs
-------
baseline_manifest.json
ridge_alpha_search.csv
metrics_per_horizon.csv
metrics_summary.csv
validation_predictions.npz
test_predictions.npz
ridge_model.joblib
baseline_report.txt
figures/
    01_test_vector_rmse.png/pdf
    02_test_speed_rmse.png/pdf
    03_test_ridge_skill.png/pdf
    04_test_10min_speed_timeseries.png/pdf

Usage example
-------------
python 04_run_baseline_forecasting.py ^
    --dataset-dir "D:\\...\\SD1090_TPOS2024_Forecasting_v0_1_2" ^
    --output "D:\\...\\baseline_v0_1" ^
    --alpha-grid "0.01,0.1,1,10,100" ^
    --plots
"""

from __future__ import annotations

import argparse
import copy
import importlib.util
import json
import math
import platform
import sys
import time
import traceback
from pathlib import Path

import numpy as np
import pandas as pd


BASELINE_VERSION = "0.1.0"

DEFAULT_ALPHA_GRID = (0.01, 0.1, 1.0, 10.0, 100.0)

REQUIRED_SPLITS = ("train", "validation", "test")
REQUIRED_NPZ_KEYS = (
    "X",
    "y",
    "y_raw",
    "context_end_time_ns",
    "target_time_ns",
    "anchor_row_index",
)


def log(message: str = "") -> None:
    print(message, flush=True)


def parse_float_grid(text: str) -> tuple[float, ...]:
    values = []
    for token in text.split(","):
        token = token.strip()
        if not token:
            continue
        value = float(token)
        if value < 0.0 or not np.isfinite(value):
            raise ValueError(
                "All Ridge alpha values must be finite and >= 0."
            )
        values.append(value)

    if not values:
        raise ValueError("At least one Ridge alpha value is required.")

    return tuple(sorted(set(values)))


def load_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def require_file(path: Path) -> None:
    if not path.exists():
        raise FileNotFoundError(path)


def find_validation_flag(dataset_dir: Path) -> list[Path]:
    return sorted(
        dataset_dir.glob("validation*/VALIDATION_PASSED.flag")
    )


def load_dataset_metadata(
    dataset_dir: Path,
) -> tuple[dict, dict, pd.DataFrame]:
    manifest_path = dataset_dir / "dataset_manifest.json"
    scalers_path = dataset_dir / "scalers.json"
    split_summary_path = dataset_dir / "split_summary.csv"

    require_file(manifest_path)
    require_file(scalers_path)
    require_file(split_summary_path)

    manifest = load_json(manifest_path)
    scalers = load_json(scalers_path)
    split_summary = pd.read_csv(split_summary_path)

    return manifest, scalers, split_summary


def parse_scaler(
    scalers: dict,
    key: str,
) -> tuple[list[str], np.ndarray, np.ndarray]:
    obj = scalers[key]
    names = list(obj["names"])
    mean = np.asarray(obj["mean"], dtype=np.float64)
    std = np.asarray(obj["std"], dtype=np.float64)
    return names, mean, std


def load_npz_split(
    dataset_dir: Path,
    split: str,
) -> dict[str, np.ndarray]:
    path = dataset_dir / f"{split}.npz"
    require_file(path)

    log(f"[LOAD] {path}")

    with np.load(path, allow_pickle=False) as npz:
        missing = [
            key for key in REQUIRED_NPZ_KEYS
            if key not in npz.files
        ]
        if missing:
            raise RuntimeError(
                f"{path.name} missing required arrays: {missing}"
            )

        arrays = {
            key: npz[key]
            for key in REQUIRED_NPZ_KEYS
        }

    return arrays


def reshape_ridge_X(X: np.ndarray) -> np.ndarray:
    """
    Flatten [N, lookback, features] -> [N, lookback*features].

    np.reshape usually provides a view because X is C-contiguous in the dataset.
    """
    if X.ndim != 3:
        raise ValueError(f"Expected 3D X, got shape {X.shape}")

    return X.reshape(X.shape[0], -1)


def reshape_ridge_y(y: np.ndarray) -> np.ndarray:
    """Flatten [N, horizons, 2] -> [N, horizons*2]."""
    if y.ndim != 3:
        raise ValueError(f"Expected 3D y, got shape {y.shape}")

    return y.reshape(y.shape[0], -1)


def inverse_target_standardization(
    y_z_flat: np.ndarray,
    n_horizons: int,
    target_mean: np.ndarray,
    target_std: np.ndarray,
) -> np.ndarray:
    """
    Convert Ridge standardized flattened output to raw U/V in m/s.

    Returns
    -------
    [N, horizons, 2]
    """
    n = y_z_flat.shape[0]

    y_z = y_z_flat.reshape(
        n,
        n_horizons,
        len(target_mean),
    ).astype(np.float64, copy=False)

    y_raw = (
        y_z * target_std[None, None, :]
        + target_mean[None, None, :]
    )

    return y_raw.astype(np.float32)


def persistence_prediction(
    X: np.ndarray,
    n_horizons: int,
    feature_names: list[str],
    feature_mean: np.ndarray,
    feature_std: np.ndarray,
) -> np.ndarray:
    """
    Persistence baseline from the last observed U/V in the input context.

    X is already standardized. Recover last raw U/V via feature scaler.
    """
    try:
        u_idx = feature_names.index("UWND_MEAN")
        v_idx = feature_names.index("VWND_MEAN")
    except ValueError as exc:
        raise RuntimeError(
            "Persistence requires UWND_MEAN and VWND_MEAN in features."
        ) from exc

    uv_idx = np.asarray([u_idx, v_idx], dtype=np.int64)

    last_uv_z = X[:, -1, uv_idx].astype(
        np.float64,
        copy=False,
    )

    last_uv_raw = (
        last_uv_z
        * feature_std[uv_idx][None, :]
        + feature_mean[uv_idx][None, :]
    )

    pred = np.repeat(
        last_uv_raw[:, None, :],
        repeats=n_horizons,
        axis=1,
    )

    return pred.astype(np.float32)


def safe_r2(
    truth: np.ndarray,
    pred: np.ndarray,
) -> float:
    truth = truth.astype(np.float64, copy=False)
    pred = pred.astype(np.float64, copy=False)

    ss_res = float(np.sum((truth - pred) ** 2))
    centered = truth - np.mean(truth)
    ss_tot = float(np.sum(centered ** 2))

    if ss_tot <= 0.0:
        return float("nan")

    return 1.0 - ss_res / ss_tot


def evaluate_per_horizon(
    truth: np.ndarray,
    pred: np.ndarray,
    horizons: tuple[int, ...],
    model_name: str,
    split_name: str,
    persistence_reference: np.ndarray | None = None,
) -> pd.DataFrame:
    """
    Compute forecast metrics for each horizon.

    Parameters
    ----------
    truth, pred
        Shape [N, H, 2], raw U/V in m/s.
    """
    if truth.shape != pred.shape:
        raise ValueError(
            f"truth/pred shape mismatch: {truth.shape} vs {pred.shape}"
        )

    if truth.shape[1] != len(horizons):
        raise ValueError(
            "Number of forecast horizons does not match prediction shape."
        )

    rows = []

    for j, horizon in enumerate(horizons):
        true_uv = truth[:, j, :].astype(
            np.float64,
            copy=False,
        )
        pred_uv = pred[:, j, :].astype(
            np.float64,
            copy=False,
        )

        err = pred_uv - true_uv
        du = err[:, 0]
        dv = err[:, 1]

        u_rmse = float(np.sqrt(np.mean(du ** 2)))
        v_rmse = float(np.sqrt(np.mean(dv ** 2)))
        vector_rmse = float(
            np.sqrt(np.mean(du ** 2 + dv ** 2))
        )

        u_mae = float(np.mean(np.abs(du)))
        v_mae = float(np.mean(np.abs(dv)))
        vector_mae = float(
            np.mean(np.sqrt(du ** 2 + dv ** 2))
        )

        true_speed = np.sqrt(
            true_uv[:, 0] ** 2
            + true_uv[:, 1] ** 2
        )
        pred_speed = np.sqrt(
            pred_uv[:, 0] ** 2
            + pred_uv[:, 1] ** 2
        )

        speed_err = pred_speed - true_speed
        speed_rmse = float(
            np.sqrt(np.mean(speed_err ** 2))
        )
        speed_mae = float(np.mean(np.abs(speed_err)))

        r2_u = safe_r2(true_uv[:, 0], pred_uv[:, 0])
        r2_v = safe_r2(true_uv[:, 1], pred_uv[:, 1])

        bias_u = float(np.mean(du))
        bias_v = float(np.mean(dv))
        speed_bias = float(np.mean(speed_err))

        if persistence_reference is None:
            skill = 0.0 if model_name.lower() == "persistence" else float("nan")
        else:
            ref_uv = persistence_reference[:, j, :].astype(
                np.float64,
                copy=False,
            )
            ref_err = ref_uv - true_uv
            ref_rmse = float(
                np.sqrt(
                    np.mean(
                        ref_err[:, 0] ** 2
                        + ref_err[:, 1] ** 2
                    )
                )
            )

            if ref_rmse <= 0.0:
                skill = float("nan")
            else:
                skill = 1.0 - vector_rmse / ref_rmse

        rows.append({
            "split": split_name,
            "model": model_name,
            "horizon_min": int(horizon),
            "n_samples": int(len(true_uv)),
            "U_RMSE_mps": u_rmse,
            "V_RMSE_mps": v_rmse,
            "vector_RMSE_mps": vector_rmse,
            "U_MAE_mps": u_mae,
            "V_MAE_mps": v_mae,
            "vector_MAE_mps": vector_mae,
            "speed_RMSE_mps": speed_rmse,
            "speed_MAE_mps": speed_mae,
            "R2_U": r2_u,
            "R2_V": r2_v,
            "R2_mean": float(np.nanmean([r2_u, r2_v])),
            "bias_U_mps": bias_u,
            "bias_V_mps": bias_v,
            "speed_bias_mps": speed_bias,
            "skill_vs_persistence": skill,
        })

    return pd.DataFrame(rows)


def summarize_metrics(
    per_horizon: pd.DataFrame,
) -> pd.DataFrame:
    rows = []

    group_cols = ["split", "model"]

    for (split_name, model_name), grp in per_horizon.groupby(
        group_cols,
        sort=False,
    ):
        rows.append({
            "split": split_name,
            "model": model_name,
            "n_horizons": int(len(grp)),
            "mean_vector_RMSE_mps": float(
                grp["vector_RMSE_mps"].mean()
            ),
            "mean_vector_MAE_mps": float(
                grp["vector_MAE_mps"].mean()
            ),
            "mean_speed_RMSE_mps": float(
                grp["speed_RMSE_mps"].mean()
            ),
            "mean_speed_MAE_mps": float(
                grp["speed_MAE_mps"].mean()
            ),
            "mean_R2": float(
                grp["R2_mean"].mean()
            ),
            "mean_skill_vs_persistence": float(
                grp["skill_vs_persistence"].mean()
            ),
        })

    return pd.DataFrame(rows)


def save_predictions(
    path: Path,
    truth: np.ndarray,
    persistence: np.ndarray,
    ridge: np.ndarray,
    context_end_time_ns: np.ndarray,
    target_time_ns: np.ndarray,
    horizons: tuple[int, ...],
) -> None:
    np.savez_compressed(
        path,
        truth_uv=np.asarray(truth, dtype=np.float32),
        persistence_uv=np.asarray(
            persistence,
            dtype=np.float32,
        ),
        ridge_uv=np.asarray(ridge, dtype=np.float32),
        context_end_time_ns=np.asarray(
            context_end_time_ns,
            dtype=np.int64,
        ),
        target_time_ns=np.asarray(
            target_time_ns,
            dtype=np.int64,
        ),
        horizons_min=np.asarray(
            horizons,
            dtype=np.int64,
        ),
    )


def load_sci_style(script_dir: Path):
    style_path = script_dir / "sci_plot_style.py"

    if not style_path.exists():
        log(
            f"[PLOT WARNING] sci_plot_style.py not found: {style_path}"
        )
        return None

    spec = importlib.util.spec_from_file_location(
        "sci_plot_style",
        str(style_path),
    )

    if spec is None or spec.loader is None:
        return None

    module = importlib.util.module_from_spec(spec)
    sys.modules["sci_plot_style"] = module
    spec.loader.exec_module(module)

    if hasattr(module, "apply_sci_style"):
        try:
            selected = module.apply_sci_style(
                base_font_size=8.5
            )
        except TypeError:
            try:
                selected = module.apply_sci_style(
                    font_size=8.5
                )
            except TypeError:
                selected = module.apply_sci_style()

        log(
            f"[PLOT] SCI style applied; "
            f"selected_font={selected}"
        )

    return module


def make_plots(
    metrics: pd.DataFrame,
    test_truth: np.ndarray,
    test_persistence: np.ndarray,
    test_ridge: np.ndarray,
    test_target_time_ns: np.ndarray,
    horizons: tuple[int, ...],
    output_dir: Path,
    example_hours: float,
) -> None:
    import matplotlib.pyplot as plt
    import matplotlib.dates as mdates

    style = load_sci_style(
        Path(__file__).resolve().parent
    )

    fig_dir = output_dir / "figures"
    fig_dir.mkdir(parents=True, exist_ok=True)

    def finish(ax, grid=True):
        if style is not None and hasattr(style, "clean_axis"):
            style.clean_axis(ax, grid=grid)
        elif style is not None and hasattr(style, "finish_axes"):
            style.finish_axes(ax, grid=grid)
        else:
            ax.tick_params(
                which="both",
                direction="in",
                top=True,
                right=True,
            )
            if grid:
                ax.grid(True, alpha=0.25)

    def save(fig, name):
        base = fig_dir / name

        if style is not None and hasattr(style, "save_figure"):
            style.save_figure(fig, base)
        else:
            fig.savefig(
                base.with_suffix(".png"),
                dpi=600,
                bbox_inches="tight",
            )
            fig.savefig(
                base.with_suffix(".pdf"),
                bbox_inches="tight",
            )
            plt.close(fig)

    test_metrics = metrics.loc[
        metrics["split"] == "test"
    ].copy()

    # --------------------------------------------------------
    # Figure 1: vector RMSE vs horizon.
    # --------------------------------------------------------
    fig, ax = plt.subplots(figsize=(3.6, 2.8))

    for model_name in ["Persistence", "Ridge"]:
        grp = test_metrics.loc[
            test_metrics["model"] == model_name
        ].sort_values("horizon_min")

        ax.plot(
            grp["horizon_min"],
            grp["vector_RMSE_mps"],
            marker="o",
            label=model_name,
        )

    ax.set_xlabel("Forecast horizon (min)")
    ax.set_ylabel(r"Vector RMSE (m s$^{-1}$)")
    ax.set_xticks(list(horizons))
    ax.legend(loc="best")
    finish(ax, grid=True)
    save(fig, "01_test_vector_rmse")

    # --------------------------------------------------------
    # Figure 2: wind-speed RMSE vs horizon.
    # --------------------------------------------------------
    fig, ax = plt.subplots(figsize=(3.6, 2.8))

    for model_name in ["Persistence", "Ridge"]:
        grp = test_metrics.loc[
            test_metrics["model"] == model_name
        ].sort_values("horizon_min")

        ax.plot(
            grp["horizon_min"],
            grp["speed_RMSE_mps"],
            marker="o",
            label=model_name,
        )

    ax.set_xlabel("Forecast horizon (min)")
    ax.set_ylabel(r"Speed RMSE (m s$^{-1}$)")
    ax.set_xticks(list(horizons))
    ax.legend(loc="best")
    finish(ax, grid=True)
    save(fig, "02_test_speed_rmse")

    # --------------------------------------------------------
    # Figure 3: Ridge skill vs persistence.
    # --------------------------------------------------------
    ridge_grp = test_metrics.loc[
        test_metrics["model"] == "Ridge"
    ].sort_values("horizon_min")

    fig, ax = plt.subplots(figsize=(3.6, 2.8))
    ax.plot(
        ridge_grp["horizon_min"],
        ridge_grp["skill_vs_persistence"],
        marker="o",
    )
    ax.axhline(0.0, linewidth=0.8)
    ax.set_xlabel("Forecast horizon (min)")
    ax.set_ylabel("Skill vs persistence")
    ax.set_xticks(list(horizons))
    finish(ax, grid=True)
    save(fig, "03_test_ridge_skill")

    # --------------------------------------------------------
    # Figure 4: example speed time series at longest horizon.
    # --------------------------------------------------------
    j = len(horizons) - 1

    true_speed = np.sqrt(
        test_truth[:, j, 0].astype(np.float64) ** 2
        + test_truth[:, j, 1].astype(np.float64) ** 2
    )
    persistence_speed = np.sqrt(
        test_persistence[:, j, 0].astype(np.float64) ** 2
        + test_persistence[:, j, 1].astype(np.float64) ** 2
    )
    ridge_speed = np.sqrt(
        test_ridge[:, j, 0].astype(np.float64) ** 2
        + test_ridge[:, j, 1].astype(np.float64) ** 2
    )

    target_times = pd.to_datetime(
        test_target_time_ns[:, j],
        unit="ns",
        utc=True,
    )

    if len(target_times) > 0:
        start_time = target_times[0]
        end_time = start_time + pd.Timedelta(
            hours=float(example_hours)
        )
        mask = target_times <= end_time
    else:
        mask = np.zeros(
            len(target_times),
            dtype=bool,
        )

    fig, ax = plt.subplots(figsize=(7.2, 3.0))

    ax.plot(
        target_times[mask],
        true_speed[mask],
        label="Observed",
    )
    ax.plot(
        target_times[mask],
        persistence_speed[mask],
        label="Persistence",
    )
    ax.plot(
        target_times[mask],
        ridge_speed[mask],
        label="Ridge",
    )

    ax.set_xlabel("Time")
    ax.set_ylabel(r"Wind speed (m s$^{-1}$)")
    ax.legend(loc="best", ncol=3)

    locator = mdates.AutoDateLocator(
        minticks=4,
        maxticks=8,
    )
    ax.xaxis.set_major_locator(locator)
    ax.xaxis.set_major_formatter(
        mdates.ConciseDateFormatter(locator)
    )

    finish(ax, grid=True)
    save(
        fig,
        f"04_test_{horizons[j]}min_speed_timeseries",
    )


def main() -> int:
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--dataset-dir",
        required=True,
        help=(
            "Validated forecasting dataset directory created by "
            "02_build_forecasting_dataset.py"
        ),
    )
    parser.add_argument(
        "--output",
        default=None,
        help=(
            "Output directory. Default: "
            "<dataset-dir>/baseline_v0_1"
        ),
    )
    parser.add_argument(
        "--alpha-grid",
        default=",".join(
            str(v) for v in DEFAULT_ALPHA_GRID
        ),
        help=(
            "Comma-separated Ridge alpha candidates. "
            "Default: 0.01,0.1,1,10,100"
        ),
    )
    parser.add_argument(
        "--ridge-solver",
        default="lsqr",
        choices=[
            "auto",
            "svd",
            "cholesky",
            "lsqr",
            "sparse_cg",
            "sag",
            "saga",
            "lbfgs",
        ],
        help="scikit-learn Ridge solver. Default: lsqr.",
    )
    parser.add_argument(
        "--ridge-tol",
        type=float,
        default=1e-4,
        help="Ridge solver tolerance. Default: 1e-4.",
    )
    parser.add_argument(
        "--ridge-max-iter",
        type=int,
        default=5000,
        help="Maximum Ridge iterations. Default: 5000.",
    )
    parser.add_argument(
        "--example-hours",
        type=float,
        default=24.0,
        help=(
            "Length of example test time-series figure in hours. "
            "Default: 24."
        ),
    )
    parser.add_argument(
        "--skip-validation-flag",
        action="store_true",
        help=(
            "Allow execution without VALIDATION_PASSED.flag. "
            "Not recommended for the frozen SCI workflow."
        ),
    )
    parser.add_argument(
        "--plots",
        action="store_true",
        help="Generate SCI-style PNG/PDF figures.",
    )

    args = parser.parse_args()

    dataset_dir = Path(args.dataset_dir)
    output_dir = (
        Path(args.output)
        if args.output is not None
        else dataset_dir / "baseline_v0_1"
    )
    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    alpha_grid = parse_float_grid(
        args.alpha_grid
    )

    log("=" * 88)
    log("SAILDRONE BASELINE FORECASTING")
    log("=" * 88)
    log(f"baseline_version : {BASELINE_VERSION}")
    log(f"dataset_dir      : {dataset_dir}")
    log(f"output_dir       : {output_dir}")
    log(f"alpha_grid       : {list(alpha_grid)}")
    log(f"ridge_solver     : {args.ridge_solver}")
    log(f"ridge_tol        : {args.ridge_tol}")
    log(f"ridge_max_iter   : {args.ridge_max_iter}")
    log("")

    # ------------------------------------------------------------------
    # Stage 1: validation gate and metadata.
    # ------------------------------------------------------------------
    log("[STAGE 1/8] Validation gate and dataset metadata")

    validation_flags = find_validation_flag(
        dataset_dir
    )

    if not validation_flags and not args.skip_validation_flag:
        raise RuntimeError(
            "No VALIDATION_PASSED.flag was found under the dataset directory.\n"
            "Run 03_validate_forecasting_dataset.py first, or explicitly use "
            "--skip-validation-flag if you intentionally want to bypass this gate."
        )

    if validation_flags:
        log("[OK] Validation flag(s):")
        for path in validation_flags:
            log(f"     {path}")
    else:
        log(
            "[WARNING] Validation flag gate bypassed "
            "by --skip-validation-flag"
        )

    manifest, scalers, split_summary = (
        load_dataset_metadata(dataset_dir)
    )

    horizons = tuple(
        int(v)
        for v in manifest[
            "forecast_horizons_minutes"
        ]
    )
    lookback = int(
        manifest["lookback_minutes"]
    )
    feature_names = list(
        manifest["feature_names"]
    )
    target_names = list(
        manifest["target_names"]
    )

    feature_scaler_names, feature_mean, feature_std = (
        parse_scaler(
            scalers,
            "feature_scaler",
        )
    )
    target_scaler_names, target_mean, target_std = (
        parse_scaler(
            scalers,
            "target_scaler",
        )
    )

    if feature_scaler_names != feature_names:
        raise RuntimeError(
            "Feature scaler names do not match dataset manifest."
        )

    if target_scaler_names != target_names:
        raise RuntimeError(
            "Target scaler names do not match dataset manifest."
        )

    if target_names != [
        "UWND_MEAN",
        "VWND_MEAN",
    ]:
        raise RuntimeError(
            "This baseline script currently expects U/V targets."
        )

    log(f"[OK] Lookback : {lookback} min")
    log(f"[OK] Horizons : {list(horizons)} min")
    log(f"[OK] Features : {len(feature_names)}")
    log(f"[OK] Targets  : {target_names}")

    # Import sklearn here for clearer environment error.
    try:
        import sklearn
        from sklearn.linear_model import Ridge
        import joblib
    except Exception as exc:
        raise RuntimeError(
            "scikit-learn/joblib are required for the Ridge baseline. "
            "Install them in the active WindDL environment."
        ) from exc

    # ------------------------------------------------------------------
    # Stage 2: load training and validation arrays.
    # ------------------------------------------------------------------
    log("[STAGE 2/8] Loading train and validation splits")

    train = load_npz_split(
        dataset_dir,
        "train",
    )
    validation = load_npz_split(
        dataset_dir,
        "validation",
    )

    X_train = train["X"]
    y_train = train["y"]
    X_val = validation["X"]
    y_val_raw = validation["y_raw"]

    X_train_2d = reshape_ridge_X(
        X_train
    )
    y_train_2d = reshape_ridge_y(
        y_train
    )
    X_val_2d = reshape_ridge_X(
        X_val
    )

    log(
        f"[OK] Ridge train matrix: "
        f"{X_train_2d.shape}"
    )
    log(
        f"[OK] Ridge target matrix: "
        f"{y_train_2d.shape}"
    )
    log(
        f"[OK] Ridge validation matrix: "
        f"{X_val_2d.shape}"
    )

    # Persistence validation prediction is independent of Ridge.
    persistence_val = persistence_prediction(
        X=X_val,
        n_horizons=len(horizons),
        feature_names=feature_names,
        feature_mean=feature_mean,
        feature_std=feature_std,
    )

    # ------------------------------------------------------------------
    # Stage 3: Ridge alpha search on validation only.
    # ------------------------------------------------------------------
    log("[STAGE 3/8] Ridge alpha search on validation split")

    alpha_rows = []
    best_score = float("inf")
    best_alpha = None
    best_model = None
    best_val_pred = None

    for alpha in alpha_grid:
        log(f"[RIDGE] alpha={alpha:g}")

        start = time.perf_counter()

        model = Ridge(
            alpha=float(alpha),
            fit_intercept=True,
            solver=args.ridge_solver,
            tol=float(args.ridge_tol),
            max_iter=int(args.ridge_max_iter),
        )

        model.fit(
            X_train_2d,
            y_train_2d,
        )

        val_pred_z_flat = model.predict(
            X_val_2d
        )

        val_pred_raw = inverse_target_standardization(
            y_z_flat=val_pred_z_flat,
            n_horizons=len(horizons),
            target_mean=target_mean,
            target_std=target_std,
        )

        metric_df = evaluate_per_horizon(
            truth=y_val_raw,
            pred=val_pred_raw,
            horizons=horizons,
            model_name="Ridge",
            split_name="validation",
            persistence_reference=persistence_val,
        )

        score = float(
            metric_df["vector_RMSE_mps"].mean()
        )

        elapsed = float(
            time.perf_counter() - start
        )

        mean_skill = float(
            metric_df[
                "skill_vs_persistence"
            ].mean()
        )

        log(
            f"        mean vector RMSE={score:.6f} m/s, "
            f"mean skill={mean_skill:.4f}, "
            f"time={elapsed:.1f} s"
        )

        alpha_rows.append({
            "alpha": float(alpha),
            "validation_mean_vector_RMSE_mps": score,
            "validation_mean_skill_vs_persistence": mean_skill,
            "fit_and_validation_seconds": elapsed,
        })

        if score < best_score:
            best_score = score
            best_alpha = float(alpha)
            best_model = copy.deepcopy(model)
            best_val_pred = val_pred_raw.copy()

    if best_model is None or best_val_pred is None:
        raise RuntimeError(
            "Ridge alpha search did not produce a valid model."
        )

    alpha_search_df = pd.DataFrame(
        alpha_rows
    ).sort_values(
        "alpha"
    )

    alpha_search_df.to_csv(
        output_dir / "ridge_alpha_search.csv",
        index=False,
        encoding="utf-8-sig",
    )

    log(
        f"[SELECTED] alpha={best_alpha:g}, "
        f"validation mean vector RMSE="
        f"{best_score:.6f} m/s"
    )

    # ------------------------------------------------------------------
    # Stage 4: validation metrics for selected Ridge + persistence.
    # ------------------------------------------------------------------
    log("[STAGE 4/8] Final validation metrics")

    val_persistence_metrics = evaluate_per_horizon(
        truth=y_val_raw,
        pred=persistence_val,
        horizons=horizons,
        model_name="Persistence",
        split_name="validation",
        persistence_reference=None,
    )

    val_ridge_metrics = evaluate_per_horizon(
        truth=y_val_raw,
        pred=best_val_pred,
        horizons=horizons,
        model_name="Ridge",
        split_name="validation",
        persistence_reference=persistence_val,
    )

    save_predictions(
        output_dir / "validation_predictions.npz",
        truth=y_val_raw,
        persistence=persistence_val,
        ridge=best_val_pred,
        context_end_time_ns=validation[
            "context_end_time_ns"
        ],
        target_time_ns=validation[
            "target_time_ns"
        ],
        horizons=horizons,
    )

    # We no longer need training arrays in memory.
    del (
        train,
        X_train,
        y_train,
        X_train_2d,
        y_train_2d,
    )

    # ------------------------------------------------------------------
    # Stage 5: untouched test evaluation.
    # ------------------------------------------------------------------
    log("[STAGE 5/8] Untouched test evaluation")

    test = load_npz_split(
        dataset_dir,
        "test",
    )

    X_test = test["X"]
    y_test_raw = test["y_raw"]
    X_test_2d = reshape_ridge_X(
        X_test
    )

    persistence_test = persistence_prediction(
        X=X_test,
        n_horizons=len(horizons),
        feature_names=feature_names,
        feature_mean=feature_mean,
        feature_std=feature_std,
    )

    test_pred_z_flat = best_model.predict(
        X_test_2d
    )

    ridge_test = inverse_target_standardization(
        y_z_flat=test_pred_z_flat,
        n_horizons=len(horizons),
        target_mean=target_mean,
        target_std=target_std,
    )

    test_persistence_metrics = evaluate_per_horizon(
        truth=y_test_raw,
        pred=persistence_test,
        horizons=horizons,
        model_name="Persistence",
        split_name="test",
        persistence_reference=None,
    )

    test_ridge_metrics = evaluate_per_horizon(
        truth=y_test_raw,
        pred=ridge_test,
        horizons=horizons,
        model_name="Ridge",
        split_name="test",
        persistence_reference=persistence_test,
    )

    save_predictions(
        output_dir / "test_predictions.npz",
        truth=y_test_raw,
        persistence=persistence_test,
        ridge=ridge_test,
        context_end_time_ns=test[
            "context_end_time_ns"
        ],
        target_time_ns=test[
            "target_time_ns"
        ],
        horizons=horizons,
    )

    # ------------------------------------------------------------------
    # Stage 6: metrics tables and saved model.
    # ------------------------------------------------------------------
    log("[STAGE 6/8] Saving metrics and model")

    metrics = pd.concat(
        [
            val_persistence_metrics,
            val_ridge_metrics,
            test_persistence_metrics,
            test_ridge_metrics,
        ],
        ignore_index=True,
    )

    metrics.to_csv(
        output_dir / "metrics_per_horizon.csv",
        index=False,
        encoding="utf-8-sig",
    )

    metrics_summary = summarize_metrics(
        metrics
    )

    metrics_summary.to_csv(
        output_dir / "metrics_summary.csv",
        index=False,
        encoding="utf-8-sig",
    )

    joblib.dump(
        best_model,
        output_dir / "ridge_model.joblib",
    )

    # ------------------------------------------------------------------
    # Stage 7: manifest and human-readable report.
    # ------------------------------------------------------------------
    log("[STAGE 7/8] Writing baseline manifest and report")

    manifest_out = {
        "baseline_version": BASELINE_VERSION,
        "source_dataset_version": manifest.get(
            "dataset_version"
        ),
        "source_dataset_dir": str(
            dataset_dir.resolve()
        ),
        "validation_flags": [
            str(path.resolve())
            for path in validation_flags
        ],
        "lookback_minutes": lookback,
        "forecast_horizons_minutes": list(
            horizons
        ),
        "feature_names": feature_names,
        "target_names": target_names,
        "models": {
            "Persistence": {
                "definition": (
                    "Future U/V equals the last observed U/V "
                    "at the end of the input context."
                ),
            },
            "Ridge": {
                "input_shape": [
                    lookback,
                    len(feature_names),
                ],
                "flattened_feature_count": (
                    lookback * len(feature_names)
                ),
                "output_count": (
                    len(horizons) * len(target_names)
                ),
                "alpha_candidates": list(
                    alpha_grid
                ),
                "selected_alpha": best_alpha,
                "solver": args.ridge_solver,
                "tol": args.ridge_tol,
                "max_iter": args.ridge_max_iter,
                "hyperparameter_selection_split": "validation",
                "selection_metric": (
                    "mean vector RMSE across forecast horizons"
                ),
                "final_fit_scope": (
                    "training split only; validation used only "
                    "for alpha selection"
                ),
            },
        },
        "metric_definitions": {
            "vector_RMSE_mps": (
                "sqrt(mean((U_pred-U_true)^2 + "
                "(V_pred-V_true)^2))"
            ),
            "vector_MAE_mps": (
                "mean(sqrt((U_pred-U_true)^2 + "
                "(V_pred-V_true)^2))"
            ),
            "speed_RMSE_mps": (
                "RMSE of sqrt(U^2+V^2)"
            ),
            "skill_vs_persistence": (
                "1 - model_vector_RMSE / "
                "persistence_vector_RMSE"
            ),
        },
        "software": {
            "python": sys.version,
            "platform": platform.platform(),
            "numpy": np.__version__,
            "pandas": pd.__version__,
            "scikit_learn": sklearn.__version__,
            "joblib": joblib.__version__,
        },
        "files": {
            "ridge_alpha_search": "ridge_alpha_search.csv",
            "metrics_per_horizon": "metrics_per_horizon.csv",
            "metrics_summary": "metrics_summary.csv",
            "validation_predictions": "validation_predictions.npz",
            "test_predictions": "test_predictions.npz",
            "ridge_model": "ridge_model.joblib",
        },
    }

    with (
        output_dir / "baseline_manifest.json"
    ).open(
        "w",
        encoding="utf-8",
    ) as f:
        json.dump(
            manifest_out,
            f,
            ensure_ascii=False,
            indent=2,
        )

    test_summary = metrics_summary.loc[
        metrics_summary["split"] == "test"
    ]

    with (
        output_dir / "baseline_report.txt"
    ).open(
        "w",
        encoding="utf-8",
    ) as f:
        f.write(
            "Saildrone baseline forecasting report\n"
        )
        f.write("=" * 88 + "\n\n")
        f.write(
            f"Baseline version: {BASELINE_VERSION}\n"
        )
        f.write(
            f"Dataset version: "
            f"{manifest.get('dataset_version')}\n"
        )
        f.write(
            f"Lookback: {lookback} min\n"
        )
        f.write(
            f"Horizons: {list(horizons)} min\n"
        )
        f.write(
            f"Features: {feature_names}\n"
        )
        f.write(
            f"Selected Ridge alpha: {best_alpha}\n"
        )
        f.write(
            f"Validation mean vector RMSE "
            f"for selected alpha: "
            f"{best_score:.8f} m/s\n\n"
        )

        f.write(
            "Ridge alpha search\n"
        )
        f.write("-" * 88 + "\n")
        f.write(
            alpha_search_df.to_string(
                index=False
            )
        )
        f.write("\n\n")

        f.write(
            "Test metrics per horizon\n"
        )
        f.write("-" * 88 + "\n")
        f.write(
            metrics.loc[
                metrics["split"] == "test"
            ].to_string(
                index=False
            )
        )
        f.write("\n\n")

        f.write(
            "Test metric summary\n"
        )
        f.write("-" * 88 + "\n")
        f.write(
            test_summary.to_string(
                index=False
            )
        )
        f.write("\n")

    # ------------------------------------------------------------------
    # Stage 8: plots + concise console summary.
    # ------------------------------------------------------------------
    log("[STAGE 8/8] Finalization")

    if args.plots:
        log(
            "[PLOT] Generating SCI-style baseline figures"
        )
        make_plots(
            metrics=metrics,
            test_truth=y_test_raw,
            test_persistence=persistence_test,
            test_ridge=ridge_test,
            test_target_time_ns=test[
                "target_time_ns"
            ],
            horizons=horizons,
            output_dir=output_dir,
            example_hours=args.example_hours,
        )
        log("[OK] Figures complete")

    log("")
    log("=" * 88)
    log("TEST BASELINE RESULTS")
    log("=" * 88)

    for model_name in [
        "Persistence",
        "Ridge",
    ]:
        grp = metrics.loc[
            (metrics["split"] == "test")
            & (metrics["model"] == model_name)
        ].sort_values(
            "horizon_min"
        )

        summary_row = metrics_summary.loc[
            (metrics_summary["split"] == "test")
            & (
                metrics_summary["model"]
                == model_name
            )
        ].iloc[0]

        log(
            f"{model_name}: "
            f"mean vector RMSE="
            f"{summary_row['mean_vector_RMSE_mps']:.4f} m/s, "
            f"mean skill="
            f"{summary_row['mean_skill_vs_persistence']:.4f}"
        )

        per_horizon_text = ", ".join(
            f"{int(row.horizon_min)}min="
            f"{row.vector_RMSE_mps:.4f}"
            for row in grp.itertuples()
        )
        log(
            f"  vector RMSE: {per_horizon_text}"
        )

    log("")
    log(
        f"[SELECTED] Ridge alpha = {best_alpha:g}"
    )
    log(
        f"[DONE] Baseline outputs: {output_dir}"
    )

    return 0


if __name__ == "__main__":
    try:
        exit_code = main()
    except Exception:
        print(
            "\n[FATAL ERROR]",
            flush=True,
        )
        traceback.print_exc()
        print(
            "\nPlease send the complete traceback "
            "and terminal output.",
            flush=True,
        )
        sys.exit(1)

    sys.exit(exit_code)
